config/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import include, path

from security.conf import SecurityConf
from users.conf import ProfileConf
from foo.conf import FooConf

SECURITY_URL_PREFIX = SecurityConf.URL_PREFIX
USER_URL_PREFIX = ProfileConf.URL_PREFIX
FOO_URL_PREFIX = FooConf.URL_PREFIX

urlpatterns = i18n_patterns(
    path("", include("core.urls", namespace="core")),
    path("", include("app.urls")),
    path("api/", include("app.api.urls", namespace="api")),
    path("djangoadmin/", admin.site.urls),
    path("{0}/".format(SECURITY_URL_PREFIX), include("security.urls", namespace="security")),
    path("{0}/".format(USER_URL_PREFIX), include("users.urls", namespace="users")),
    path("{0}/".format(FOO_URL_PREFIX), include("foo.urls", namespace="foo")),

    prefix_default_language=False
)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path("__debug__/", include(debug_toolbar.urls)),
    ]

playground/app/urls.py
from django.conf import settings
from django.urls import path
from django.views.generic import TemplateView

from .views import (
    AppSessionView, HomeView
)

app_name = "app"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("app-session/", AppSessionView.as_view(), name="app_session"),

]

if settings.DEBUG:
    urlpatterns += [
        path("404", TemplateView.as_view(template_name="404.html"))
    ]

playground/app/templates/base.html
<!DOCTYPE html>
{% load static %}
{% load core_extras %}
{% load i18n %}

<html lang="en">

<head>

<meta http-equiv="content-type" content="text/html; charset=utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">

<title>
{% block title %}{% endblock title %} | {{ project_name }}
</title>

<link rel="icon" href="{% static 'favicon.ico' %}">

{% block stylesheets %}

<link rel="stylesheet" href="{% static 'css/app.css' %}" />
<link rel="stylesheet" href="{% static 'css/fontawesome-all.css' %}" />

{% endblock stylesheets %}

{% block styles %}
<style>

.notifications {
  position: fixed;
  top: 0;
  z-index: 2000;
  width: 100%;
}

.navbar-dropdown {
  margin-right: 5px;
}

.user-nav-avatar {
  min-width: 40px;
  min-height: 40px;
}

</style>
{% endblock styles %}

</head>

<body class="{% block body_classes %}theme-cloudy{% endblock body_classes %}" style="min-height: 100vh;">

<div id="app-container">

{% block navbar %}
<nav class="navbar is-bordered" role="navigation" aria-label="main navigation">

<div class="navbar-brand">

<a
id="navbar-sidebar-trigger"
class="sidebar-trigger" 
aria-label="navbar-sidebar-trigger" 
@click.prevent="toggleSidebar"
>
<span></span>
<span></span>
<span></span>
</a>

<a class="navbar-item navbar-logo" href="{% url 'app:home' %}">
<img src="{% static 'images/cfs-logo-sm.png' %}" alt="cfs-logo">
</a>

</div>

<div 
id="navbar-menu" 
class="navbar-menu"
ref="navbarMenu"
>

<div class="navbar-end">

{% include "includes/_user_nav.html" %}

</div><!-- navbar -->

</div><!-- navbar-menu -->

</nav><!-- navbar -->

{% endblock navbar %}

{% block sidebar %}
<div id="sidebar-background" class="sidebar-background" @click="toggleSidebar(false)"></div>

<div
id="sidebar"
class="sidebar"
ref="sidebar"
>
<div class="sidebar-container">

<div class="sidebar-navbar">

<a 
id="sidebar-trigger"
class="sidebar-trigger" 
aria-label="sidebar-trigger" 
@click.prevent="toggleSidebar"
>
<span></span>
<span></span>
<span></span>
</a>

<a class="navbar-item navbar-logo" href="{% url 'app:home' %}">
<img src="{% static 'images/cfs-logo-sm.png' %}" alt="cfs-logo">
</a>

</div>

<div class="sidebar-body">

{% block sidebar_nav_items %}

<div class="menu">

{% if user.is_authenticated %}

  <p class="menu-label">
  {% trans "label_your_menu" %}
  </p>

  <ul class="menu-list">

  <li class="sidebar-divider"></li>

  </ul>

{% endif %}

<p class="menu-label">
{% trans "label_general" %}
</p>

<ul class="menu-list">

<li>
<a 
class="{% block home_link_active %}{% endblock home_link_active %}"
href="{% url 'app:home' %}"
>
<i class="fas fa-fw fa-home menu-icon"></i> {% trans "label_home" %}
</a>
</li>

</ul>

</div>

{% endblock sidebar_nav_items %}

</div><!-- end sidebar-body -->

<div class="sidebar-footer">

<dropdown
id="sidebar-language-selector"
dropdown-classes="is-up"
>

<template slot="dropdown-label">
{% trans "label_language" %}: {{ LANGUAGE_CODE|upper }}
</template>

<template slot="dropdown-content">
{% get_language_info_list for LANGUAGES as languages %}

{% for language in languages %}

  <a id="sidebar-{{ language.code }}" class="dropdown-item" href="{% change_language language.code %}">
  {{ language.name_translated }}
  </a>

{% endfor %}
</template>

</dropdown>

</div><!-- end sidebar-footer -->

</div>
</div><!-- end sidebar -->
{% endblock sidebar %}

{% block top_messages %}

<div id="messages">
{% include "includes/_messages.html" %}
</div><!-- messages -->

{% endblock top_messages %}

{% block notifications %}

<div id="notifications" class="notifications">
{% include "includes/_queued_notifications.html" %}
</div>

{% endblock notifications %}

{% block ws_notifications %}
<div id="ws-notifications">

</div>
{% endblock ws_notifications %}

{% block full_width_sections %}{% endblock full_width_sections %}

{% block content_container %}

<section class="section {% block main_section_classes %}main-content{% endblock main_section_classes %}">
<div class="columns">
<div class="column is-10 is-offset-1">

{% block content_top %}{% endblock content_top %}

{% block content %}{% endblock content %}

</div>
</div>
</section>

{% endblock content_container %}

{% block page_footer %}
<footer class="page-footer">

{% now "Y" %} | {{ project_name }}

</footer>
{% endblock page_footer %}

{% block modal_content %}{% endblock modal_content %}

</div><!-- app-container -->

<script>
{# Block reserved for JavaScript variables whose values come from backend Python content #}
{% block python_to_javascript %}

// If enabled, maintain sidebar's state between requests.
var initSidebarSessionEnabled = false; 
var sidebarExpanded = false;
var appSessionUrl = "{% url 'app:app_session' %}";

{% endblock python_to_javascript %}
</script>

{% block scripts %}
<script src="{% static 'js/utils.js' %}"></script>
<script src="{% static 'js/showdown.min.js' %}"></script>
<script src="{% static 'js/reconnecting-websocket.min.js' %}"></script>
<script src="{% static 'js/axios.min.js' %}"></script>
<script src="{% static 'js/ajax.js' %}"></script>
<script src="{% static 'js/vue.js' %}"></script>
<script src="{% static 'js/vue/plugins/modal.js' %}"></script>
<script src="{% static 'js/vue/core-components.js' %}"></script>
<script src="{% static 'js/vue/app-components.js' %}"></script>
<script src="{% static 'js/vue/notifications.js' %}"></script>
<script src="{% static 'js/notification-websocket.js' %}"></script>
<script src="{% static 'js/vue/directives/vue-scrollto.js' %}"></script>
<script src="{% static 'js/vue/app.js' %}"></script>

{% endblock scripts %}

</body>
</html>

playground/app/templates/base_error.html
<!DOCTYPE html>
{% load static %}
{% load core_extras %}
{% load i18n %}

<html lang="en">

<head>

<meta http-equiv="content-type" content="text/html; charset=utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">

<title>
{% block title %}{% endblock title %}
</title>

<link rel="icon" href="{% static 'favicon.ico' %}">

{% block stylesheets %}

<link rel="stylesheet" href="{% static 'css/app.css' %}" />
<link rel="stylesheet" href="{% static 'css/fontawesome-all.css' %}" />

<style>
.response-error-header {
  font-size: 80px;
}

.response-error-text {
  font-size: 22px;
}
</style>

{% endblock stylesheets %}

</head>

<body class="{% block body_classes %}theme-cloudy{% endblock body_classes %}">

{% block body %}

<div class="centerall">
<div class="columns is-multiline is-centered">
{% block content %}{% endblock content %}
</div>
</div>

{% endblock body %}

</body>
</html>

playground/app/templates/googleb7077bd8f7f710c0.html
google-site-verification: googleb7077bd8f7f710c0.html

playground/app/templates/home.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}

{% trans 'page_home_title' %}

{% endblock title %}

{% block home_link_active %}is-active{% endblock home_link_active %}

{% block full_width_sections %}
<section id="intro" class="parallax-block intro">

<div class="columns">
<div class="column">

<div class="parallax-body">

<h1 class="is-size-1 is-size-2-mobile"> {{ project_name }} </h1>

<h2 class="is-size-3 is-size-4-mobile">
{% trans 'msg_project_desc' %}
</h2>

</div>

</div>
</div>

</section>

<div class="page-sections">

<section class="section page-section icon-blocks">

<div class="columns">
<div class="column is-10 is-offset-1">

<h2 class="page-section-header">{% trans "msg_project_at_a_glance" %}</h2>

<div class="columns is-multiline">

<div class="column is-6 icon-block">

<header class="icon-block-header">

<i class="fas fa-book-open icon-block-icon"></i>

<h3>{% trans "msg_block_1" %}</h3>

</header>

<p>
{% trans "msg_block_1_desc" %}
</p>

</div>

<div class="column is-6 icon-block">

<i class="fas fa-book-open icon-block-icon"></i>

<header class="icon-block-header">
<h3>{% trans "msg_block_2" %}</h3>
</header>

<p>
{% trans "msg_block_2_desc" %}
</p>

</div>

</div>

</div>
</div>

</section>
</div>
{% endblock full_width_sections %}

{% block content %}
{% endblock content %}