config/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import include, path

from security.conf import SecurityConf
from users.conf import ProfileConf
from foo.conf import FooConf

SECURITY_URL_PREFIX = SecurityConf.URL_PREFIX
USER_URL_PREFIX = ProfileConf.URL_PREFIX
FOO_URL_PREFIX = FooConf.URL_PREFIX

urlpatterns = i18n_patterns(
    path("", include("core.urls", namespace="core")),
    path("", include("app.urls")),
    path("api/", include("app.api.urls", namespace="api")),
    path("djangoadmin/", admin.site.urls),
    path("{0}/".format(SECURITY_URL_PREFIX), include("security.urls", namespace="security")),
    path("{0}/".format(USER_URL_PREFIX), include("users.urls", namespace="users")),
    path("{0}/".format(FOO_URL_PREFIX), include("foo.urls", namespace="foo")),

    prefix_default_language=False
)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path("__debug__/", include(debug_toolbar.urls)),
    ]

playground/app/urls.py
from django.conf import settings
from django.urls import path
from django.views.generic import TemplateView

from .views import (
    AppSessionView, HomeView
)

app_name = "app"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("app-session/", AppSessionView.as_view(), name="app_session"),

]

if settings.DEBUG:
    urlpatterns += [
        path("404", TemplateView.as_view(template_name="404.html"))
    ]

playground/security/urls.py
from django.urls import path

from .views import LoginView, LogoutView

app_name = 'security'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

playground/users/urls.py
from django.urls import include, path, re_path

from .views import (
    ProfileDetailView,
    UserForgotPasswordRequestView, UserForgotPasswordResetView
)
from .views_auth import (
    ProfileUpdateView, UserPasswordResetView
)

app_name = 'users'

auth_urls = [
    re_path(
        r'^(?P<username>[0-9A-Za-z_\-\.]+)/update/$',
        ProfileUpdateView.as_view(),
        name='profile_update'
    ),
]

urlpatterns = [
    re_path(
        r'^(?P<username>[0-9A-Za-z_\-\.]+)/$',
        ProfileDetailView.as_view(),
        name='profile_view'
    ),
    path(
        'forgot-password/',
        UserForgotPasswordRequestView.as_view(),
        name='user_password_reset_request'
    ),
    re_path(
        r'^forgot-password-reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        UserForgotPasswordResetView.as_view(),
        name='user_forgot_password_reset'
    ),
    path(
        'update/<slug:username>/password-reset/',
        UserPasswordResetView.as_view(),
        name='user_password_reset'
    ),
    path('auth/', include(auth_urls)),
]

playground/security/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.utils.translation import ugettext_lazy as _


class LoginForm(AuthenticationForm):
    username = forms.CharField(
        label=_('label_username'),
        required=True,
        error_messages={
            'required': _('validation_field_required'),
        }
    )
    password = forms.CharField(
        label=_('label_password'),
        widget=forms.PasswordInput,
        error_messages={
            'required': _('validation_field_required'),
        }
    )
    error_messages = {
        'invalid_login': _('validation_invalid_login'),
        'inactive': _('validation_inactive_user')
    }

    def __init__(self, *args, **kwargs):
        kwargs.setdefault('auto_id', '%s')
        kwargs.setdefault('label_suffix', '')
        super(LoginForm, self).__init__(*args, **kwargs)

playground/security/views.py
from django.contrib.auth import REDIRECT_FIELD_NAME, login as auth_login, logout as auth_logout
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.utils.http import is_safe_url
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.debug import sensitive_post_parameters
from django.views.generic import FormView, View

from .conf import settings
from .forms import LoginForm


class LoginView(FormView):
    '''
    Provides the ability to login as a user with a username and password
    '''
    form_class = LoginForm
    redirect_field_name = REDIRECT_FIELD_NAME
    redirect_next_url = None
    template_name = 'security/login.html'

    @method_decorator(sensitive_post_parameters('password'))
    @method_decorator(csrf_protect)
    @method_decorator(never_cache)
    def dispatch(self, request, *args, **kwargs):
        self.redirect_next_url = request.GET.get(self.redirect_field_name, '')
        # If user already logged in, redirect.
        if request.user.is_authenticated:
            return HttpResponseRedirect(reverse(settings.LOGIN_REDIRECT_URL))
        # Sets a test cookie to make sure the user has cookies enabled.
        request.session.set_test_cookie()
        return super(LoginView, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        auth_login(self.request, form.get_user())
        # If the test cookie worked, go ahead and
        # delete it since it's no longer needed.
        if self.request.session.test_cookie_worked():
            self.request.session.delete_test_cookie()
        return super(LoginView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(LoginView, self).get_context_data(**kwargs)
        context['next'] = self.request.GET.get(self.redirect_field_name, '')
        return context

    def get_success_url(self):
        redirect_to = self.request.POST.get('next', '')
        url_is_safe = is_safe_url(redirect_to, allowed_hosts={settings.PROJECT_DOMAIN})
        if redirect_to and redirect_to != reverse('app:home') and url_is_safe:
            return redirect_to
        else:
            return reverse(settings.LOGIN_REDIRECT_URL)


class LogoutView(View):

    def get(self, request, *args, **kwargs):
        auth_logout(request)
        return HttpResponseRedirect(reverse(settings.LOGOUT_REDIRECT_URL))

playground/app/templates/security/login.html
{% extends "base.html" %}
{% load static %}
{% load core_extras %}
{% load widget_tweaks %}
{% load i18n %}

{% block title %}
{% trans "page_login_title" %}
{% endblock title %}

{% block navbar %}{% endblock navbar %}
{% block sidebar %}{% endblock sidebar %}

{% block content_container %}
<div class="centerall">

<div class="columns is-multiline is-centered is-desktop">

<div class="column is-12 has-text-centered">

<a href="{% url 'app:home' %}">
<img src="{% static 'images/cfs-logo-header.png' %}" class="header-logo" alt="logo">
</a>

</div>

<div class="column is-12">

<form 
id="login-form" 
action="{% if next %}{% url_set_param 'security:login' next=next %}{% else %}{% url 'security:login' %}{% endif %}" 
method="post" 
novalidate>
{% csrf_token %}
{{ form.non_field_errors }}

<div class="field">

<div class="control has-icons-left">

{% trans "placeholder_username" as placeholder_username %}
{% render_field form.username class+="input" placeholder+=placeholder_username %}

<span class="icon is-small is-left">
<i class="fas fa-user"></i>
</span>

</div>

{{ form.username.errors }}

</div>

<div class="field">

<div class="control has-icons-left">

{% trans "placeholder_password" as placeholder_password %}
{% render_field form.password class+="input" placeholder+=placeholder_password %}

<span class="icon is-small is-left">
<i class="fas fa-lock"></i>
</span>

</div>

{{ form.password.errors }}

</div>

<button class="button is-info" type="submit">
{% trans "label_login" %}
</button>

<input type="hidden" name="next" value="{{ next }}" >

</form>

<div style="margin-top: 20px;">
<a href="{% url 'users:user_password_reset_request' %}">{% trans "msg_forgot_password_q" %}</a>
</div>

</div>
</div>

</div>
{% endblock content_container %}

{% block page_footer %}{% endblock page_footer %}